from cherry import app, db
from werkzeug.exceptions import Forbidden

@app.route("/sections/<course_id>")
def sections(course_id: str):
    sections = list(db["sections"].find({"course_id": course_id}))
    # removing unique identifier generated by MongoDB
    for sec in sections:
        del sec["_id"]
    response = {"sections": sections}
    print(response["sections"])
    return response